apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgbearer.fullname" . }}
  labels:
    {{- include "pgbearer.labels" . | nindent 4 }}
data:
  pgbearer.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
